### ISSUE TITLE
Website completely broken in safari

### ISSUE THREAD

**Issue by ssneilss** [jshuaf/Aquaforces#104]
#### Process:
- Open Safari browser(mobile/ desktop) and visit aquaforces.com
- Error messages pop out as follow:
  <img width="1263" alt="2016-08-30 10 01 34" src="https://cloud.githubusercontent.com/assets/7845386/18093808/ccaf673a-6f03-11e6-954f-881fdba22fd8.png">

**Comment by jshuaf** [comment]
Looks like we need to get webpack to add shared files, specifically those in `/http/a/scripts`.
