### ISSUE TITLE
Application crashes when playing

### ISSUE THREAD

**Issue by ssneilss** [jshuaf/Aquaforces#108]
#### Process
- Visit aquaforces.io/play or localhost:3000/play
- Open Google Chrome and start game as a host
- Create two new tabs and enter crew number 1 
- Start Game
- Wait for a moment and the screen freezes in the browser
- Cannot close the tab anymore unless force shutting down the browser

<img width="1440" alt="2016-08-31 11 36 10" src="https://cloud.githubusercontent.com/assets/7845386/18115129/6536e3c8-6f6f-11e6-8e7f-6120bf4de86f.png">

 p.s. CPU % increases in server & browser, have to restart the server to make the whole website normal again. looks like an infinite loop? No errors showing though

**Comment by alexandernext** [comment]
@pppp22591558 I can't seem to access aquaforces.io?

**Comment by ssneilss** [comment]
@alexandernext sorry it was broken after testing :/ restarted already

**Comment by ssneilss** [comment]
<img width="1144" alt="2016-08-31 1 10 22" src="https://cloud.githubusercontent.com/assets/7845386/18116663/55db366a-6f7c-11e6-8373-c11bfde61bf2.png">

**Comment by jshuaf** [comment]
I'll look into this.

**Comment by jshuaf** [comment]
Perhaps #90 was wrong -- something else is breaking the CPU.

**Comment by jshuaf** [comment]
@pppp22591558 @alexandernext FIGURED IT OUT - currently working on a fix.
