### ISSUE TITLE
Application still doesn't work in Safari

### ISSUE THREAD

**Issue by ssneilss** [jshuaf/Aquaforces#115]
#### Process
- Open Safari and visit aquaforces.com/host
- See the errors below:

<img width="1440" alt="2016-09-01 10 16 15" src="https://cloud.githubusercontent.com/assets/7845386/18153069/911d55ee-702d-11e6-9dee-2dec6da4c984.png">

**Comment by jshuaf** [comment]
You need to run `npm run build`. It's not a code issue as I can run it locally on the master branch...

**Comment by jshuaf** [comment]
@pppp22591558 let me know if that works.

**Comment by ssneilss** [comment]
I ran
- `npm run build`
- `npm run producition`
  Is it right?

**Comment by jshuaf** [comment]
Fixed.
