### ISSUE TITLE
Cannot view question sets

### ISSUE THREAD

**Issue by ssneilss** [jshuaf/Aquaforces#117]
#### Process
- Open Google Chrome and visit aquaforces.com/console
- Click on "Math Counts" it will show no "Correct Answer" and "Incorrect Answer"
- Back to question sets list by clicking "View Sets"
- Click on "Definition(1)" or "Definition(2)" and see the errors below:

<img width="1440" alt="2016-09-01 10 53 38" src="https://cloud.githubusercontent.com/assets/7845386/18153805/639dc11c-7032-11e6-831e-a0e6fe16b8b3.png">

*Looks like you miss assigning a shortID to the question set

**Comment by jshuaf** [comment]
Yeah... so I've fixed this in #120. But we should look into schema validation for our database.
