### ISSUE TITLE
WEBSOCKETS ARE BROKEN

### ISSUE THREAD

**Issue by jshuaf** [jshuaf/Aquaforces#123]
@pppp22591558 I need you to take a look at this

https://github.com/socketio/socket.io/issues/1942

Right now on aquaforces.com nothing works - the sockets are closing for some odd reason. I think it's because of nginx. Could you take a look?

**Comment by ssneilss** [comment]
I fixed it temporarily now
It's because of the ssl + google cloud load balancer
Still figuring it out but right now it's all normal

*FYI I had another project using socket.io with other settings similar to Aquaforces and it worked.

**Comment by jshuaf** [comment]
Still broken for me...

**Comment by ssneilss** [comment]
It's so weird I refreshed a couple of times and it worked again....

**Comment by alexandernext** [comment]
Has this by any chance been fixed?

**Comment by jshuaf** [comment]
Same as #126.
