### ISSUE TITLE
Set editing/viewing

### ISSUE THREAD

**Issue by alexandernext** [jshuaf/Aquaforces#124]
Shouldn't we just combine editing and viewing into one thing -- ie the editing screen?

**Comment by jshuaf** [comment]
I'm against this for a few reasons -
1. set editing and viewing are VERY different - you shouldn't give up the UX of one of them just to make it more "simple"
2. this will quickly become cluttered with buttons that aren't relevant to what the user is intending
3. this would require refactorization

It makes more sense to me to have it the current way - new sets and editing sets have similar UX.

**Comment by alexandernext** [comment]
@jshuaf what exactly do you envision set "viewing" looking like tho?

**Comment by jshuaf** [comment]
you can view all of the questions... and their answers. eventually statistics will be there

**Comment by alexandernext** [comment]
but like UI wise how is it supposed to look if we separate the two

**Comment by jshuaf** [comment]
One is input fields... one is viewing.
