### ISSUE TITLE
Server might not respond immediately, causing potential for double joining

### ISSUE THREAD

**Issue by alexandernext** [jshuaf/Aquaforces#37]

**Comment by jshuaf** [comment]
what do u mean

**Comment by janisfuh** [comment]
as in from the same person?

**Comment by alexandernext** [comment]
two join crew thing were being sent cuz it didnt disappear b4 the server responded which wasn't immediate

**Comment by jshuaf** [comment]
as in double button clicks?

**Comment by janisfuh** [comment]
yeah it happened to me just noww

**Comment by alexandernext** [comment]
@janisfuh just replicated this
This doesn't work!! BIG ISSUE!

**Comment by jshuaf** [comment]
fixing now

**Comment by jshuaf** [comment]
just so we're on the same page whats the issue

**Comment by alexandernext** [comment]
so basically when we go through the joining process the server takes time to process the additions and in the process some people may join twice cuz they click the button twice -- that's an issue

**Comment by alexandernext** [comment]
also it create problems down the road

**Comment by jshuaf** [comment]
i can't reproduce cuz i have 100mb wifi lmao but i can fix it

**Comment by alexandernext** [comment]
throttle it chrome dev tools

**Comment by jshuaf** [comment]
wait that's a thing?

**Comment by alexandernext** [comment]
yes @jshuaf
