### ISSUE TITLE
Game freezes over

### ISSUE THREAD

**Issue by alexandernext** [jshuaf/Aquaforces#78]
See title -- the game freezes over and you cant even open chrome dev tools (or just right click even)

**Comment by alexandernext** [comment]
Could be just taking up too much resources

**Comment by jshuaf** [comment]
Does it happen when you leave the tab and come back after a bit of time? Or just right away?

**Comment by alexandernext** [comment]
Leaving the tab

**Comment by jshuaf** [comment]
Just reproduced, I'm not sure what the problem is.

**Comment by jshuaf** [comment]
I've confirmed the problem is excessive CPU usage animating river reflections and answers. I'm looking into it.

**Comment by alexandernext** [comment]
We should talk over this with designers to see whether we got alternatives -- it probably makes more sense to use an image

**Comment by jshuaf** [comment]
svg animation might be something to look into.
