### ISSUE TITLE
Add back river reflections.

### ISSUE THREAD

**Issue by jshuaf** [jshuaf/Aquaforces#90]
Okay, so basically we have a problem with these river reflections. The current implementation is killing the CPU and freezing the game very quickly (see #78), so I've disabled them for now. 

The current implementation of river reflections (pseudocode):

``` javascript
updateRiverReflections() {
  forEach riverReflection:
    if (justHad correctAnswer) {
      const newPosition = calculatePosition(riverReflection.oldPosition)
      setState({newPosition})
    else {
      // see above, calculate position and set state
    }

    if (riverReflection.isWayOffScreen) remove(riverReflection)
    if (bottomReflectionIsTooHigh) addBottomReflection()
    if (topReflectionIsTooLow) addTopReflection()
}
```

Basically having to iterate over the whole list of river reflection groups every time and perform some calculations... not to mention dispatching functions that will respectively iterate over the list AGAIN in order to either
- add groups (generate a position that doesn't collide with the current ones) or 
- remove groups (know which one to remove)

So... this obviously can't all happen in the 16ms we get in `requestAnimationFrame`

**Comment by alexandernext** [comment]
Maybe we can just switch to images -- but we should talk to designers about this @janisfuh

**Comment by ssneilss** [comment]
I think using html5 canvas might be a solution? it uses GPU to render (only if the calculation functions don't take too much effort to run for browser I think

**Comment by jshuaf** [comment]
That would work, but would require a major refactorization as we're currently rendering them as React components. It could get messy to try to coerce the DOM and canvas to work together.

**Comment by ssneilss** [comment]
yeah true lemme take a look first

**Comment by alexandernext** [comment]
Would it work if the boat is moving most of the time and the only time the river reflections need to move is when the boat is about to move off the screen, in which case this function is triggered?

**Comment by jshuaf** [comment]
So you want the boat to move instead of the river reflections?

**Comment by alexandernext** [comment]
@jshuaf Yeah that makes it a lot easier computationally?

**Comment by jshuaf** [comment]
hm... it would change the feel of the game a lot. you'd have to deal with a camera

**Comment by alexandernext** [comment]
@jshuaf let's talk over this at the meeting
