### ISSUE TITLE
Set up beta testing site

### ISSUE THREAD

**Issue by alexandernext** [jshuaf/Aquaforces#91]
For designers to see what's going on

**Comment by ssneilss** [comment]
@alexandernext I would like to deploy the Aquaforces using nginx and pushion passenger (for more efficient content serving and debugging
meanwhile writing down the process to establish a server environment and all the commands-to-run/ setups

what do you think?

FYI: [Making Node.js deployment enjoyable](https://vimeo.com/phusionnl/review/84945384/73fe7432ee)

**Comment by jshuaf** [comment]
Hmmm... I don't really know much about nginx but phusion passenger looks fine to me.

Relevant links (for Alex):
- https://github.com/phusion/passenger/wiki/Phusion-Passenger%3A-Node.js-tutorial#understanding_passenger
- https://www.phusionpassenger.com/

**Comment by ssneilss** [comment]
it's the best match with node.js I could find so far for website hosting
- some benefits (but not all): http://stackoverflow.com/questions/16770673/using-node-js-only-vs-using-node-js-with-apache-nginx

**Comment by jshuaf** [comment]
Looks good. Let's do it!

**Comment by alexandernext** [comment]
@pppp22591558 @jshuaf That seems pretty nice! Are there any drawbacks we should consider?

**Comment by ssneilss** [comment]
@alexandernext Just need some time to set up but that's just an one time cost :/ 
I will try it first and maybe you should open a server for designers if in hurry

**Comment by ssneilss** [comment]
Will finish it before the weekend ends!

**Comment by alexandernext** [comment]
@pppp22591558 no worries we're not really in a hurry

**Comment by ssneilss** [comment]
The how-to guide to start a server with nginx/ passenger/ nodejs/ mongoDB: https://github.com/jshuaf/Aquaforces/wiki/Aquaforces-Development-Guide
